import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../hooks/useAuth'
import { apiFetch, fmt, daysUntil } from '../lib/api'

function fmtDate(str) {
  if (!str) return '—'
  const d = new Date(str)
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  d.setHours(0, 0, 0, 0)
  const diff = Math.round((d - today) / 86400000)
  if (diff === 0) return 'Today'
  if (diff === 1) return 'Tomorrow'
  if (diff === -1) return 'Yesterday'
  if (diff < 0) return `${Math.abs(diff)}d ago`
  return new Date(str).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

function buildTasks(d) {
  const tasks = []
  for (const f of (d.todayFocus || [])) {
    const days = f.due_date ? daysUntil(f.due_date) : 0
    tasks.push({ id: `focus-${f.id}`, title: f.description || f.counterparty || 'Action required', sub: f.amount ? `${fmt(f.amount)} IDR · ${fmtDate(f.due_date)}` : fmtDate(f.due_date), type: f.entityType || f.type || 'task', days, urgent: days <= 0, source: 'focus' })
  }
  for (const r of (d.reminders || [])) {
    const days = r.remind_at ? daysUntil(r.remind_at) : 0
    if (days > 30) continue
    tasks.push({ id: `reminder-${r.id}`, title: r.title || r.description || 'Reminder', sub: fmtDate(r.remind_at), type: 'reminder', days, urgent: days <= 0, source: 'reminder' })
  }
  for (const debt of (d.debts || []).filter(x => !x.is_settled && daysUntil(x.due_date) <= 0)) {
    tasks.push({ id: `debt-${debt.id}`, title: debt.type === 'receivable' ? `Collect from ${debt.counterparty}` : `Pay ${debt.counterparty}`, sub: `${fmt(debt.amount)} IDR · ${Math.abs(daysUntil(debt.due_date))}d overdue`, type: debt.type, days: daysUntil(debt.due_date), urgent: true, source: 'debt' })
  }
  for (const debt of (d.debts || []).filter(x => !x.is_settled && daysUntil(x.due_date) > 0 && daysUntil(x.due_date) <= 7)) {
    tasks.push({ id: `upcoming-${debt.id}`, title: debt.type === 'receivable' ? `Follow up with ${debt.counterparty}` : `Prepare payment: ${debt.counterparty}`, sub: `${fmt(debt.amount)} IDR · ${fmtDate(debt.due_date)}`, type: debt.type, days: daysUntil(debt.due_date), urgent: false, source: 'debt' })
  }
  return tasks
}

const TYPE_CFG = {
  receivable: { icon: '↓', bg: 'var(--green-light)', color: 'var(--green-dark)' },
  payable:    { icon: '↑', bg: 'var(--red-light)',   color: 'var(--red-dark)' },
  reminder:   { icon: '🔔', bg: 'var(--amber-light)', color: 'var(--amber-dark)' },
  task:       { icon: '✓', bg: 'var(--brand-light)',  color: 'var(--brand-dark)' },
  payroll:    { icon: '💼', bg: 'var(--bg-3)',         color: 'var(--text-3)' },
}

function TaskCard({ task, onDone }) {
  const tc = TYPE_CFG[task.type] || TYPE_CFG.task
  return (
    <div className={`task-card${task.urgent ? ' task-card-urgent' : ''}`}>
      <div className="task-card-icon" style={{ background: tc.bg, color: tc.color }}>{tc.icon}</div>
      <div className="task-card-body">
        <div className="task-card-title">{task.title}</div>
        <div className="task-card-sub" style={{ color: task.urgent ? 'var(--red-dark)' : undefined }}>
          {task.sub}
        </div>
      </div>
      {task.urgent && (
        <div className="hf-badge hf-badge-red" style={{ fontSize: 11 }}>Urgent</div>
      )}
      <button className="task-card-btn" onClick={onDone}>Done</button>
    </div>
  )
}

export default function Tasks() {
  const { token }  = useAuth()
  const navigate   = useNavigate()
  const [data, setData]       = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState('')
  const [done, setDone]       = useState({})

  useEffect(() => {
    apiFetch('/pulse', token)
      .then(setData)
      .catch(e => setError(e.message))
      .finally(() => setLoading(false))
  }, [token])

  if (loading && !data) return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 80 }}>
      <div style={{ width: 28, height: 28, border: '2.5px solid var(--border-2)', borderTopColor: 'var(--brand)', borderRadius: '50%', animation: 'tx-spin 0.7s linear infinite' }} />
    </div>
  )

  const d     = data || {}
  const tasks = buildTasks(d).filter(t => !done[t.id])

  const urgentTasks   = tasks.filter(t => t.urgent)
  const todayTasks    = tasks.filter(t => !t.urgent && t.days === 0)
  const upcomingTasks = tasks.filter(t => !t.urgent && t.days > 0)

  const markDone = (id) => setDone(p => ({ ...p, [id]: true }))

  return (
    <div className="hf-page">

      {/* ── Header ─── */}
      <div className="hf-page-header">
        <div>
          <div className="hf-page-title">Tasks</div>
          <div className="hf-page-subtitle">Operational and financial focus — auto-generated by AI CFO</div>
        </div>
        {tasks.length > 0 && (
          <div className="hf-badge hf-badge-blue" style={{ fontSize: 13, padding: '6px 14px' }}>
            {tasks.length} open
          </div>
        )}
      </div>

      {error && <div className="page-error" style={{ marginBottom: 20 }}>{error}</div>}

      {tasks.length === 0 && Object.keys(done).length === 0 ? (
        <div className="empty-state">
          <div className="empty-state-icon">✅</div>
          <div className="empty-state-title">All clear</div>
          <div className="empty-state-sub">AI CFO will create tasks when financial actions need attention — overdue items, upcoming payments, and follow-ups appear here automatically.</div>
          <button className="empty-state-cta" onClick={() => navigate('/')}>Back to Pulse</button>
        </div>
      ) : (
        <>
          {/* Urgent */}
          {urgentTasks.length > 0 && (
            <div style={{ marginBottom: 28 }}>
              <div className="hf-section-title" style={{ color: 'var(--red-dark)' }}>
                🔴 Urgent · {urgentTasks.length}
              </div>
              {urgentTasks.map(t => <TaskCard key={t.id} task={t} onDone={() => markDone(t.id)} />)}
            </div>
          )}

          {/* Today */}
          {todayTasks.length > 0 && (
            <div style={{ marginBottom: 28 }}>
              <div className="hf-section-title">Today · {todayTasks.length}</div>
              {todayTasks.map(t => <TaskCard key={t.id} task={t} onDone={() => markDone(t.id)} />)}
            </div>
          )}

          {/* Upcoming */}
          {upcomingTasks.length > 0 && (
            <div style={{ marginBottom: 28 }}>
              <div className="hf-section-title">Upcoming · {upcomingTasks.length}</div>
              {upcomingTasks.map(t => <TaskCard key={t.id} task={t} onDone={() => markDone(t.id)} />)}
            </div>
          )}

          {/* Completed this session */}
          {Object.keys(done).length > 0 && (
            <div style={{ marginBottom: 20 }}>
              <div className="hf-section-title" style={{ color: 'var(--green-dark)' }}>
                ✅ Completed this session · {Object.keys(done).length}
              </div>
              <div style={{ fontSize: 'var(--text-sm)', color: 'var(--text-4)', padding: '4px 0' }}>
                Tasks are marked done for this session and will reappear if still outstanding on next load.
              </div>
            </div>
          )}
        </>
      )}

      <div style={{ textAlign: 'center', paddingBottom: 8 }}>
        <button className="link-btn" onClick={() => navigate('/')}>View Pulse dashboard →</button>
      </div>
    </div>
  )
}
